name: Liquibase Migration

on:
  push:
    branches:
      - main # Cambia a la rama principal o a la que quieras monitorear

jobs:
  liquibase:
    runs-on: ubuntu-latest # Puedes cambiar el sistema operativo si lo necesitas

    steps:
            
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Configurar entorno
      run: |
        # Instala Java (necesario para Liquibase)
        sudo apt-get update -y
        sudo apt-get install -y default-jre
        
        # Instala Liquibase        
        wget https://github.com/liquibase/liquibase/releases/download/v4.23.2/liquibase-4.23.2.zip
        unzip liquibase-4.23.2.zip

        ./liquibase --help        
        ./liquibase init project

    - name: Clean Up
      run: |
        rm liquibase-4.23.2.zip
        rm -rf liquibase-4.23.2
        